return {
	diagnostic = {
		error = "󰅙",
		warn = "",
		info = "",
		hint = "",
	},
	git = {
		added = "",
		unstaged = "",
		staged = "",
		unmerged = "",
		renamed = "",
		copied = "",
		type_changed = "",
		untracked = "",
		deleted = "",
		ignored = "",
	},
	ui = {
		expanded = "",
		collapsed = "",
	},
	markdown_heading = {
		"󰉫",
		"󰉬",
		"󰉭",
		"󰉮",
		"󰉯",
		"󰉰",
	},
	debug = {
		current_frame = "",
		breakpoint = "",
		breakpoint_rejected = "",
		breakpoint_conditional = "",
	},
	status = {
		success = "",
		current_session = "",
		available_session = "",
	},
	lsp_kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
}
