CompileFlags:
  Add: [-Wall, -pedantic, -D DLOCAL, -I/Library/Developer/CommandLineTools/usr/include]
---
If:
  # PathExclude: [.*\.c$, .*\.h$]
  PathExclude: [.*\.c$]
CompileFlags:
  Add: [-std=c++2b]
