return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		run_on_start = false,
		ensure_installed = {
			"asmfmt",
			"black",
			"clang-format",
			"cmakelang",
			"codelldb",
			"cpplint",
			"delve",
			"gofumpt",
			"google-java-format",
			"java-debug-adapter",
			"java-test",
			"jdtls",
			"ktfmt",
			"ktlint",
			"latexindent",
			"lemminx",
			"prettierd",
			"rust_analyzer",
			"selene",
			"shellcheck",
			"shfmt",
			"stylua",
			"tree-sitter-cli",
			"vale",
			"vimls",
		},
	},
}
