monitorBarOverrides = []
monitorDwindleOverrides = []
monitorGapOverrides = []
monitorNiriOverrides = []
monitorOrientationOverrides = []

[appearance]
mode = "dark"

[borders]
enabled = false
width = 1.5

[borders.color]
alpha = 1.0
blue = 0.4156862497329712
green = 0.33725491166114807
red = 0.2980392277240753

[clipboard]
historyEnabled = false
maxItemBytes = 8388608
maxItems = 200
maxTotalBytes = 67108864

[dwindle]
defaultSplitRatio = 1.0
moveToRootStable = true
singleWindowAspectRatio = "fill"
smartSplit = false
splitWidthMultiplier = 1.0
useGlobalGaps = true

[focus]
crossesMonitorAtEdge = true
followsMouse = false
followsWindowToMonitor = false
moveCrossesMonitorAtEdge = true
moveMouseToFocusedWindow = false

[gaps]
size = 2.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 2.0

[general]
animationsEnabled = true
defaultLayoutType = "dwindle"
hotkeysEnabled = true
hyperKeyHoldThresholdMilliseconds = 150
hyperTrigger = "Left Option"
ipcEnabled = true
preventSleepEnabled = false
spacesTrackingEnabled = true
systemHyperTrigger = "None"
updateChecksEnabled = true

[gestures]
fingerCount = 3
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0
trackpadScrollStyle = "snap"

[mouseWarp]
enabled = false
margin = 1

[niri]
alwaysCenterSingleColumn = true
centerFocusedColumn = "never"
columnWidthPresets = [0.3333333333333333, 0.5, 0.66, 1.0]
defaultColumnWidth = 0.5
infiniteLoop = false
maxVisibleColumns = 2
singleWindowAspectRatio = "1440x1080"

[quakeTerminal]
animationDuration = 0.2
autoHide = false
enabled = false
heightPercent = 50.0
monitorMode = "focusedWindow"
opacity = 1.0
position = "center"
widthPercent = 50.0

[routing]
mode = "custom"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.0
deduplicateAppIcons = false
enabled = true
height = 28.0
hideEmptyWorkspaces = true
labelFontSize = 12.0
notchAware = false
position = "overlappingMenuBar"
reserveLayoutSpace = false
showFloatingWindows = false
showLabels = true
windowLevel = "normal"
xOffset = -395.0
yOffset = 2.0

[workspaceBar.accentColor]
alpha = 1.0
blue = 0.6745098233222961
green = 0.5058823823928833
red = 0.36862748861312866

[workspaceBar.textColor]
alpha = 1.0
blue = 0.9137254953384399
green = 0.8705881834030151
red = 0.8470587730407715

[[appRules]]
assignToWorkspace = "1"
bundleId = "com.github.williamhCode.neogurt"
id = "F8BA9DF7-A08E-4B82-A75A-DE11EFEBF615"

[[appRules]]
assignToWorkspace = "1"
bundleId = "net.kovidgoyal.kitty"
id = "22312A07-1FDD-4854-9F37-F98D9D67768E"

[[appRules]]
axRole = "AXWindow"
axSubrole = "AXStandardWindow"
bundleId = "company.thebrowser.Browser"
id = "544B5DBF-84D1-4ACC-9147-44A93184ED17"
layout = "float"

[[appRules]]
bundleId = "org.keepassxc.keepassxc"
id = "C475ED39-419C-4A85-9DD9-D665BF43FA64"
layout = "float"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.apple.iCal"
id = "1974D011-A04A-48AE-BED5-4A9FF953843B"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.apple.reminders"
id = "F916F4C9-CE81-4494-BB7A-5A15620F2B0B"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.apple.MobileSMS"
id = "9547C967-7564-4C38-9FFB-2CE16DF31DA4"

[[appRules]]
assignToWorkspace = "3"
bundleId = "md.obsidian"
id = "6A134C16-32C6-405F-AF80-7F8B06772E8E"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.hnc.Discord"
id = "B9FD25D2-1044-4796-A977-AEAD1977E03A"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "org.jeffvli.feishin"
id = "4390AA5F-1960-41BF-942B-F7337E6B6585"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "org.nicotine_plus.Nicotine"
id = "D00B2184-510D-4B0C-98D7-89E854E5B289"
layout = "tile"

[[appRules]]
axRole = "AXWindow"
axSubrole = "AXDialog"
bundleId = "org.nicotine_plus.Nicotine"
id = "419D43F6-C353-4170-8FD2-E175A510B50E"
layout = "float"

[[appRules]]
axRole = "AXWindow"
axSubrole = "AXStandardWindow"
bundleId = "org.keepassxc.keepassxc"
id = "EC40A903-4A80-4F79-86CF-B5E59F4236B8"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
axRole = "AXWindow"
axSubrole = "AXStandardWindow"
bundleId = "org.keepassxc.keepassxc"
id = "9459C5D8-AEC9-47C0-98B7-3A9422F767DC"
layout = "tile"

[[appRules]]
bundleId = "dev.moergolayerviz.local"
id = "E91ECE23-733D-4E21-911D-7ECB84F4F31C"
layout = "float"

[[appRules]]
bundleId = "com.apple.iCal"
id = "69FAF5D3-9D47-4514-A507-DE8B6BD8D051"
layout = "float"
titleRegex = "^$"

[[hotkeys]]
binding = "Control+1"
id = "switchWorkspace.0"

[[hotkeys]]
binding = "Control+Option+1"
id = "moveToWorkspace.0"

[[hotkeys]]
binding = "Control+2"
id = "switchWorkspace.1"

[[hotkeys]]
binding = "Control+Option+2"
id = "moveToWorkspace.1"

[[hotkeys]]
binding = "Control+3"
id = "switchWorkspace.2"

[[hotkeys]]
binding = "Control+Option+3"
id = "moveToWorkspace.2"

[[hotkeys]]
binding = "Control+4"
id = "switchWorkspace.3"

[[hotkeys]]
binding = "Control+Option+4"
id = "moveToWorkspace.3"

[[hotkeys]]
binding = "Control+5"
id = "switchWorkspace.4"

[[hotkeys]]
binding = "Control+Option+5"
id = "moveToWorkspace.4"

[[hotkeys]]
binding = "Control+6"
id = "switchWorkspace.5"

[[hotkeys]]
binding = "Control+Option+6"
id = "moveToWorkspace.5"

[[hotkeys]]
binding = "Control+7"
id = "switchWorkspace.6"

[[hotkeys]]
binding = "Control+Option+7"
id = "moveToWorkspace.6"

[[hotkeys]]
binding = "Control+8"
id = "switchWorkspace.7"

[[hotkeys]]
binding = "Control+Option+8"
id = "moveToWorkspace.7"

[[hotkeys]]
binding = "Control+9"
id = "switchWorkspace.8"

[[hotkeys]]
binding = "Control+Option+9"
id = "moveToWorkspace.8"

[[hotkeys]]
binding = "Option+Tab"
id = "workspaceBackAndForth"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.next"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.previous"

[[hotkeys]]
binding = "Option+H"
id = "focus.left"

[[hotkeys]]
binding = "Option+J"
id = "focus.down"

[[hotkeys]]
binding = "Option+K"
id = "focus.up"

[[hotkeys]]
binding = "Option+L"
id = "focus.right"

[[hotkeys]]
binding = "Unassigned"
id = "focusPrevious"

[[hotkeys]]
binding = "Unassigned"
id = "focusDownOrLeft"

[[hotkeys]]
binding = "Unassigned"
id = "focusUpOrRight"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowToWorkspaceUp"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspaceUp"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.0"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.1"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.2"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.3"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.4"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.5"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.6"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.7"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.8"

[[hotkeys]]
binding = "Control+Option+H"
id = "move.left"

[[hotkeys]]
binding = "Control+Option+J"
id = "move.down"

[[hotkeys]]
binding = "Control+Option+K"
id = "move.up"

[[hotkeys]]
binding = "Control+Option+L"
id = "move.right"

[[hotkeys]]
binding = "Unassigned"
id = "focusMonitorNext"

[[hotkeys]]
binding = "Unassigned"
id = "focusMonitorPrevious"

[[hotkeys]]
binding = "Unassigned"
id = "focusMonitorLast"

[[hotkeys]]
binding = "Option+Return"
id = "toggleFullscreen"

[[hotkeys]]
binding = "Unassigned"
id = "toggleNativeFullscreen"

[[hotkeys]]
binding = "Control+Option+Shift+H"
id = "moveColumn.left"

[[hotkeys]]
binding = "Control+Option+Shift+L"
id = "moveColumn.right"

[[hotkeys]]
binding = "Option+T"
id = "toggleColumnTabbed"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumnFirst"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumnLast"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.0"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.1"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.2"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.3"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.4"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.5"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.6"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.7"

[[hotkeys]]
binding = "Unassigned"
id = "focusColumn.8"

[[hotkeys]]
binding = "Option+Period"
id = "cycleColumnWidthForward"

[[hotkeys]]
binding = "Option+Comma"
id = "cycleColumnWidthBackward"

[[hotkeys]]
binding = "Option+Shift+F"
id = "toggleColumnFullWidth"

[[hotkeys]]
binding = "Option+Shift+B"
id = "balanceSizes"

[[hotkeys]]
binding = "Unassigned"
id = "moveToRoot"

[[hotkeys]]
binding = "Unassigned"
id = "toggleSplit"

[[hotkeys]]
binding = "Unassigned"
id = "swapSplit"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.down"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.left"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.right"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.up"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselectClear"

[[hotkeys]]
binding = "Unassigned"
id = "openCommandPalette"

[[hotkeys]]
binding = "Control+Option+R"
id = "raiseAllFloatingWindows"

[[hotkeys]]
binding = "Control+Option+Shift+R"
id = "rescueOffscreenWindows"

[[hotkeys]]
binding = "Control+Option+Delete"
id = "toggleFocusedWindowFloating"

[[hotkeys]]
binding = "Unassigned"
id = "assignFocusedWindowToScratchpad"

[[hotkeys]]
binding = "Unassigned"
id = "toggleScratchpadWindow"

[[hotkeys]]
binding = "Unassigned"
id = "openMenuAnywhere"

[[hotkeys]]
binding = "Unassigned"
id = "toggleWorkspaceBarVisibility"

[[hotkeys]]
binding = "Unassigned"
id = "toggleHiddenBar"

[[hotkeys]]
binding = "Option+Grave"
id = "toggleQuakeTerminal"

[[hotkeys]]
binding = "Unassigned"
id = "toggleWorkspaceLayout"

[[hotkeys]]
binding = "Option+Shift+O"
id = "toggleOverview"

[[monitorRoutingOverrides]]
gridColumn = 1
gridRow = 0
monitorDisplayId = 1
monitorName = "Built-in Retina Display"

[[monitorRoutingOverrides]]
gridColumn = 0
gridRow = 0
monitorName = "Sidecar Display (AirPlay)"

[[workspaces]]
id = "AD36F001-C57E-41A5-AC1D-DF5249D007F0"
layoutType = "dwindle"
name = "1"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "454CECD4-5E9D-4ED1-95D7-979D48817F5F"
layoutType = "niri"
name = "2"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "BEB842B5-E894-4791-9FD1-397C3CDD3538"
layoutType = "niri"
name = "3"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "248AA883-2261-4D45-943C-79C0E46A232B"
layoutType = "niri"
name = "4"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "8B8C45D6-CE9E-41D9-BD50-BE4989D5E3DE"
layoutType = "niri"
name = "5"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "F3B9368C-4FBE-4EB2-BA67-571E94E3D081"
layoutType = "default"
name = "6"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "5E83B317-6070-475F-AEEE-2715F992C0FF"
layoutType = "default"
name = "7"

[workspaces.monitorAssignment]
type = "secondary"
