require "user.setup.cmp"
require "user.setup.telescope"
require "user.setup.gitsigns"
require "user.setup.nvim-treesitter"
require "user.setup.nvim-autopairs"
require "user.setup.comment"
require "user.setup.nvim-tree"
-- require "user.setup.neo-tree"
require "user.setup.bufferline"
require "user.setup.lualine"
require "user.setup.toggleterm"
require "user.setup.project_nvim"
-- require "user.setup.illuminate"
require "user.setup.indent_blankline"
require "user.setup.alpha"
require "user.setup.dap"
require "user.setup.eyeliner"
require "user.setup.nvim_web_devicons"
require "user.setup.luasnip"
require "user.setup.toggleterm"
-- require "user.setup.kitty-runner"
require "user.setup.virt-column"
require "user.setup.nvim-colorizer"
-- require "user.setup.lspsaga"
require "user.setup.persistence"
